### ISSUE TITLE
Write tests and setup CircleCI for tests

### ISSUE THREAD

**Issue by martynchamberlin** [ChessCom/browser-extension#1]

**Comment by jeffreydunaway** [comment]
Beta version CircleCI BitBucket is now available mind you!

**Comment by martynchamberlin** [comment]
@jeffreydunaway I'm confused. Are you advocating moving this repo from Github to Bitbucket?

**Comment by jeffreydunaway** [comment]
@martynchamberlin Mirror mirror on the wall, who forks best of them all?
