### ISSUE TITLE
Show icons per alert type

### ISSUE THREAD

**Issue by wistcc** [ChessCom/browser-extension#42]
We are already showing how many alerts we have using the badge, but we don't have any shortcut to these alerts.

We should add 3 icons (maybe below the header) that tell us how many alerts specifically we have (alert-notification-games, alert-notification-messages and alert-notification-alerts) and get redirected when clicked.

**Comment by martynchamberlin** [comment]
Hi Winner,

Thanks for the suggestion. We'd love for you to create a pull request that has this feature in it!

**Comment by wistcc** [comment]
Issue closed due to [this](https://github.com/ChessCom/browser-extension/pull/44#issuecomment-259561022).
