### ISSUE TITLE
Update README with Firefox policy so it's clear to contributors in the future

### ISSUE THREAD

**Issue by wistcc** [ChessCom/browser-extension#51]
Here some things to take on count when updating the README:

* [How to run the developer mode fo Firefox](https://github.com/ChessCom/browser-extension/pull/48#issuecomment-264218199)
* [Important notes about Firefox policy](https://github.com/wistcc/browser-extension/pull/1#issue-192926645)

**Comment by martynchamberlin** [comment]
This is also a helpful tidbit: http://stackoverflow.com/a/31813035/1591507

It's helpful running `chrome.storage.local.clear()` when you want to experience the extension as a first time user.
