### ISSUE TITLE
Avoid page refresh whenever a style reset occurs

### ISSUE THREAD

**Issue by martynchamberlin** [ChessCom/browser-extension#63]
Right now, whenever a user tries to reset a UI customization, the Chess.com page refreshes. We have to do this refresh with our current setup because the plugin injects the stylesheet into the browser and while we could override this, we need to be able to actually remove the inject stylesheet (or at least modify it, to remove the pertinent elements) when the user clicks a reset button. 

This modification / removal of the injected stylesheet looks to be possible. http://stackoverflow.com/questions/18533820/how-do-i-remove-an-injected-css-file 

What I propose is instead of constantly manipulating this injected stylesheet every time the user resets something, we instead:

- Inject the stylesheet initially on page load, so as to avoid FOUC.
- Once this occurs, add the styling as inline
- Remove the injected stylesheet 
- Then in the future, when the user wants to reset something, simply remove the inline styling

This will avoid page refresh whenever a style reset occurs and it will make for a vastly superior user experience.

**Comment by emilgoldsmith** [comment]
I'd like to try contributing by helping out with this issue, though I'm planning right now to try fixing the bugs with Hide that seem more urgent in #70 which I created.

**Comment by emilgoldsmith** [comment]
I just created a PR #80 which is a start at trying to address this issue. Could you take a look and see if this is the right direction?
