### ISSUE TITLE
Add base shouldComponentUpdate globally (or at least many places locally)?

### ISSUE THREAD

**Issue by emilgoldsmith** [ChessCom/browser-extension#71]
Wouldn't this be a really good idea? I can already see now there are heaps of unnecessary renders of components going on, and I think this might be part of the problem with #70.

I would imagine an implementation that looked something like a BaseComponent that all React Components extend.

**Comment by martynchamberlin** [comment]
I think implementing `shouldComponentUpdate` would be a great idea!
