### ISSUE TITLE
Hide scrollbar when opening an option?

### ISSUE THREAD

**Issue by emilgoldsmith** [ChessCom/browser-extension#72]
Is it only me that feels like this is a small nuisance in the design? The extension will jump when you open an option because the scrollbar pops up and moves everything to the left.

**Comment by martynchamberlin** [comment]
I'm not noticing this on macOS or Windows. What environment are you seeing this? 

What I _am_ noticing though, now that you mention it, is that on Windows Chrome, there is not a scrollbar when there should be one. Check it out: 

<img width="575" alt="image 2017-03-13 at 2 36 33 pm 2" src="https://cloud.githubusercontent.com/assets/1827628/23872114/0a527fa6-07fb-11e7-8da2-2099dc1278d4.png">

**Comment by emilgoldsmith** [comment]
Here is my behaviour:

![scroll-bar-jump](https://cloud.githubusercontent.com/assets/18149242/23881902/667cf4b6-082b-11e7-8fd7-d69e4487d869.gif)

I run `google-chrome --disable-gpu-driver-bug-workarounds --enable-native-gpu-memory-buffers` on Ubuntu 16.04 (with a .bashrc alias, I don't type that every time ;) ).

Also, I was just thinking, would it maybe be a nicer UX if the notification bar at the bottom was fixed (and maybe the top as well?), as in the scroll only happened in the middle options part? I could create a new issue to discuss that. It might very well not be a nice feature, it was just something that came to my mind.

**Comment by emilgoldsmith** [comment]
And about your windows example: So it doesn't scroll at all? Also if you try scrolling within the window? And it cuts off where you cut off your screenshot?

**Comment by martynchamberlin** [comment]
I did some more digging on this scrollbar issue and here's the summary of it: the extension assumes that it can always be at least 498 pixels in height. This is a valid assumption in macOS, because if the main viewport is shorter than that, the extension window extends independently of the main viewport. 

![](https://cl.ly/1h1N2I2w3F1L/Image%202017-03-13%20at%209.20.59%20PM.png)

However this is not the case in Windows, as you can see here: 

![](https://cl.ly/4543311O2R2E/Image%202017-03-13%20at%209.18.42%20PM.png)

To answer this: 

> And it cuts off where you cut off your screenshot?

My screenshot actually includes the blue wallpaper of Windows 7. So Chrome is cutting off the extension window at the same time as the main window.

Now, I've confirmed that we do get scrollbars in Windows (and macOS) within the browser extension when its content height reaches a high enough value. 

![](https://cl.ly/463W1F1A012E/Image%202017-03-13%20at%209.26.59%20PM.png)

**Comment by emilgoldsmith** [comment]
Okay, so for the windows part, that's okay, intended behavior yeah? As in, we assume any computer screen is 500px, and then the user just has to enlarge the window? Or should we try making it responsive?

**Comment by martynchamberlin** [comment]
For now, that's fine. We may not have much choice. And either way, the likelihood that someone would have a Chrome window height of less than 498px seems pretty edge case.

**Comment by emilgoldsmith** [comment]
Yeah I agree, especially since extensions aren't supported on mobile Chrome

**Comment by emilgoldsmith** [comment]
What do you think about the UX concerns though for my GIF from above? The jumping when you click the bar, is it something you think that should be fixed, or is it not really an issue in your eyes? I'll admit I'm definitely more back-end oriented, but I guess I'm also a user, and it seems like a bit of an annoyance in user-experience terms.

**Comment by martynchamberlin** [comment]
I agree it's a problem, though I'm not sure the solution of hiding the scrollbar is the right one. There are a decent number of Windows users who like the ability to click and drag the scrollbar itself as their primary means of scrolling. Instead, what I'd recommend doing is [forcing a vertical scrollbar](https://css-tricks.com/snippets/css/force-vertical-scrollbar/) perpetually. It wouldn't be the most beautiful thing in the world but it would keep this from happening.

**Comment by emilgoldsmith** [comment]
Yeah I think that makes sense.

I'm not sure exactly how non-beautiful it would be, but I guess a future issue could also be trying to style it to fit the chess.com design (which by the way, I really like the design of the extension!)

**Comment by martynchamberlin** [comment]
Well the width of the scrollbar is something like 20 pixels. We could just say that on Windows, the extension width is 20 pixels wider than what it is on Mac and then that'd guarantee an even layout.

**Comment by martynchamberlin** [comment]
Right currently the plugin's width is 300 pixels everywhere. We could make it 320 pixels on Windows and force a vertical scrollbar. That way the actual width minus the scrollbar is the same on both platforms.

**Comment by emilgoldsmith** [comment]
Okay sure. I'll probably submit a PR soon that forces the vertical scrollbar, and I can put in that CSS as well and then since I don't have a Windows computer readily available, maybe you could help me check it out and see if it works well?

**Comment by martynchamberlin** [comment]
Will do! 

Btw, most of my Windows troubleshooting is done in a virtual machine via https://github.com/xdissent/ievms. In case you're ever interested in setting up something similar on your linux box. :)

**Comment by emilgoldsmith** [comment]
Cool, thanks :). I'm definitely more of a back-end coder, so I'm not sure if I'll need it, but that's definitely a cool project, so thanks for sharing!
