### ISSUE TITLE
Redundant line in ToggleDisplay.js?

### ISSUE THREAD

**Issue by emilgoldsmith** [ChessCom/browser-extension#73]
Here is the code I'm referencing from ToggleDisplay.js (line 38-48):
``` 
  save = (name, state) => {
    chrome.storage.local.get('display', result => {
      const obj = result;
      if (Object.keys(result).length === 0 && obj.constructor === Object) {
        chrome.storage.local.set({ display: {} });
        obj.display = {};
      }
      obj.display[name] = state;
      chrome.storage.local.set(obj);
    });
  }
```

I'm simply asking as I have not worked with Chrome extensions before, but it seems to me that `chrome.storage.local.set({ display: {} });` is redundant and will just cause two calls to storage in a row instead of 1, no? As far as I could understand by looking online storage.local.set should support adding a new object even though it doesn't exist?

If there's something I misunderstood feel free to close the issue right away.

If not I can submit a PR right away

**Comment by martynchamberlin** [comment]
Good point! This could be more optimized by bundling these two calls into a single call.

**Comment by emilgoldsmith** [comment]
Cool, just wanted to make sure, I'll close this when we merge in my syntax-cleaning PR later.
