### ISSUE TITLE
Fix (as in keep static) the notification bar on scroll?

### ISSUE THREAD

**Issue by emilgoldsmith** [ChessCom/browser-extension#74]
Just to open it up to discussion, topic was first mentioned in #72. 

Was also considering whether the top could maybe be fixed? But I'm more in doubt about that, where I think it could feel nice if the notification bar didn't suddenly disappear when you click an option.

**Comment by martynchamberlin** [comment]
I'd be fine with a sticky notification bar! We could see what it'd look like with the top sticky too. Agree that I'm not sold on it, but I'd be happy to have a look. The primary concern is that we don't want to infringe on people's available real estate.

**Comment by emilgoldsmith** [comment]
Yeah I definitely agree about the available real estate concern with keeping the top sticky, I think it could work well with the notification bar though. Let's implement it quickly at some point and take a look, yeah.
