### ISSUE TITLE
window(.context).chessBrowserExtension doing anything?

### ISSUE THREAD

**Issue by emilgoldsmith** [ChessCom/browser-extension#82]
Code being referred to is [here](https://github.com/ChessCom/browser-extension/blob/master/chrome/content.js#L3) and [here](https://github.com/ChessCom/browser-extension/blob/master/chrome/extension/background/inject.js#L3-L4).

Are these of some kind of use on the actual chess.com site that I don't know of what goes on on the actual site? And why would we need it on both window.context and window? I smell bug.

Also, I did a `vimgrep` and can't find any place where `injected` from the `var injected = window.chessBrowserExtension;` line in the repo, so I'm assuming that's another rogue variable that could just be deleted yeah?

**Comment by emilgoldsmith** [comment]
and if the `chessBrowserExtension` is used on Chess.com we should probably add that in some comments for future clarity.

**Comment by martynchamberlin** [comment]
So we never implemented it, but this was to let the main chess.com site know, during logging of errors, whether the user had the extension installed or not, as a part of the troubleshooting process. Let's leave this for now unless we can find a more elegant way to earmark it for the site? And I'm making a note to actually implement this so we're getting good out of it.

**Comment by emilgoldsmith** [comment]
Okay sounds good, and yeah I guessed something like that as well. Both for troubleshooting and maybe for statistics as well. But can't we agree that [this function](https://github.com/ChessCom/browser-extension/blob/master/chrome/extension/background/inject.js#L1-L7) isn't doing anything whatsoever? And maybe I should include deleting that in my #83 PR?

I mean it isn't doing anything because the `injected` variable is never used, and for your logging purpose we want the `window.context.chessBrowserExtension` that get's [here](https://github.com/ChessCom/browser-extension/blob/master/chrome/content.js#L3) yeah? Not `window.chessBrowserExtension` which I also think is bad practice putting it directly on the `window` object. 
I assume this is just another oversight of old code that should be removed in #83 because the way you did things changed and you forgot to remove something old and now it just seems weird.

**Comment by emilgoldsmith** [comment]
And yeah I'll add the comments as well if you agree with what I said above

**Comment by martynchamberlin** [comment]
Yep, we can remove that function. 

By the way, your links no longer work. That's why it's usually a good idea to link to a specific commit, since GitHub never deletes commits.

**Comment by emilgoldsmith** [comment]
Oh interesting, thanks!

I had actually just read online how it was best to do it like I did it (which is pressing y so you go to a specific blob that won't change), but I guess there are even more edge cases!

But you understand what I mean yeah?

**Comment by martynchamberlin** [comment]
Actually pressing y would be the right solution here. 

E.g. when I press y at https://github.com/ChessCom/browser-extension/blob/master/chrome/getCurrentUser.js, it takes me to https://github.com/ChessCom/browser-extension/blob/d5c3eedaee58f77354aca78bfbdb591f655593b7/chrome/getCurrentUser.js.

**Comment by emilgoldsmith** [comment]
Oh yeah you're right. I'm so sure I actually pressed y. I'm not quite sure what happened, but I can see when I hover over my links that they aren't formatted correctly. Weird!

I'll double check next time, thanks for pointing out though.
